# File: docker-compose.yml
# Version: 1.0.0
# Last Updated: 2025-04-15 12:00

version: '3.8'

services:
  farsiland-scraper:
    build: .
    container_name: farsiland-scraper
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    command: python -m farsiland_scraper.run --daemon --notify
    # Healthcheck to restart the container if it's unhealthy
    healthcheck:
      test: ["CMD", "python", "-c", "import os, time; exit(0 if os.path.exists('/app/data/site_index.json') and time.time() - os.path.getmtime('/app/data/site_index.json') < 3600 else 1)"]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 5m
    # Set resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  data:
  logs: